### ISSUE TITLE
on reading data from redis-lru throwing error

### ISSUE THREAD

**Issue by MrKanthaliya** [leohowell/redis-lru#2]
Hi, looks like here reading data is in byte format and trying to converting using json loads. should be in string format

Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/redis_lru/lru.py", line 215, in __getitem__
    value = json.loads(value)
  File "/usr/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'

**Comment by leohowell** [comment]
Sorry for my delay, I will fix this as soon as possible.

**Comment by leohowell** [comment]
please try again
